spring:
  application:
    name: MMM-admin-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/mmmdbcap
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8100


